"""empty message

Revision ID: 0df5e73efb28
Revises: f226ec55688b
Create Date: 2025-02-04 19:24:51.896434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df5e73efb28'
down_revision = 'f226ec55688b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=True))
        batch_op.drop_constraint('user_nombre_usuario_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('contraseña')
        batch_op.drop_column('nombre_completo')
        batch_op.drop_column('nombre_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre_completo', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_nombre_usuario_key', ['nombre_usuario'])
        batch_op.drop_column('password')
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
