"""empty message

Revision ID: 8bff724d674c
Revises: 8d9140e37625
Create Date: 2025-02-03 19:29:06.610572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bff724d674c'
down_revision = '8d9140e37625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=100), nullable=False),
    sa.Column('color_ojos', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('color_pelo', sa.String(length=100), nullable=False),
    sa.Column('estatura', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.String(length=40), nullable=False),
    sa.Column('color_piel', sa.String(length=20), nullable=False),
    sa.Column('hogar', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    # ### end Alembic commands ###
