"""empty message

Revision ID: dbbff74108b4
Revises: a5cffa318ac2
Create Date: 2025-02-03 19:08:23.335996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbff74108b4'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('diametro', sa.String(length=100), nullable=False),
    sa.Column('tiempo_rotacion', sa.String(length=100), nullable=False),
    sa.Column('tiempo_orbitacion', sa.String(length=100), nullable=False),
    sa.Column('gravedad', sa.String(length=100), nullable=False),
    sa.Column('poblacion', sa.String(length=100), nullable=False),
    sa.Column('clima', sa.String(length=100), nullable=False),
    sa.Column('terreno', sa.String(length=100), nullable=False),
    sa.Column('superficie_acuosa', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('contraseña', sa.String(length=80), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('contraseña')
        batch_op.drop_column('nombre')

    op.drop_table('Planetas')
    # ### end Alembic commands ###
