"""empty message

Revision ID: f226ec55688b
Revises: 246603c6f331
Create Date: 2025-02-03 19:47:38.751876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f226ec55688b'
down_revision = '246603c6f331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=80), nullable=False))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre_completo')

    # ### end Alembic commands ###
